name: CICD-EKS-Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      action:
        description: "Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - plan
          - apply
          - destroy

# ─────────────────────────────────────────────
# REQUIRED GITHUB SECRETS:
#
#   AWS_ACCOUNT_ID          → Your AWS account ID (e.g. 038462776086)
#   GITHUB_OIDC_ROLE        → IAM role name for OIDC (e.g. github-actions-role)
#   TF_STATE_BUCKET         → S3 bucket name for Terraform state
#   TF_STATE_LOCK_TABLE     → DynamoDB table name for state locking
#   TF_STATE_REGION         → AWS region for S3/DynamoDB backend (e.g. ap-south-2)
#
# REQUIRED GITHUB ENVIRONMENTS (Settings → Environments):
#   staging    → no approval required (auto-deploys)
#   production → add required reviewers for approval gate
# ─────────────────────────────────────────────

env:
  AWS_REGION: ap-south-2
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-2.amazonaws.com

jobs:
  # ──────────────────────────────────────────
  # JOB 1: Terraform Plan (runs on all triggers)
  # ──────────────────────────────────────────
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write # needed to post plan output as PR comment

    outputs:
      tf_plan_exitcode: ${{ steps.plan.outputs.exitcode }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.GITHUB_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.7"

      # ── Dynamic backend: no hardcoded values in terraform code ──
      - name: Terraform Init (Dynamic Backend)
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ github.event.inputs.environment || 'staging' }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.TF_STATE_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}" \
            -backend-config="encrypt=true" \
            -reconfigure

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var="environment=${{ github.event.inputs.environment || 'staging' }}" \
            -detailed-exitcode \
            -out=tfplan 2>&1 | tee plan_output.txt
          echo "exitcode=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT
        continue-on-error: true

      # Post plan output as a PR comment
      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('plan_output.txt', 'utf8');
            const truncated = plan.length > 60000 ? plan.substring(0, 60000) + '\n...(truncated)' : plan;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Terraform Plan\n\`\`\`hcl\n${truncated}\n\`\`\``
            });

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          retention-days: 1

      - name: Fail if Plan errored
        if: steps.plan.outputs.exitcode == '1'
        run: exit 1

  # ──────────────────────────────────────────
  # JOB 2: Deploy to STAGING
  # (auto-deploys, no approval needed)
  # ──────────────────────────────────────────
  deploy-staging:
    name: "Deploy → Staging"
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: terraform-plan
    environment: staging   # ← maps to GitHub Environment "staging"

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.GITHUB_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.7"

      - name: Terraform Init (Staging Backend)
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=staging/terraform.tfstate" \
            -backend-config="region=${{ secrets.TF_STATE_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}" \
            -backend-config="encrypt=true" \
            -reconfigure

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Terraform Apply (Staging)
        if: github.event.inputs.action != 'plan'
        run: terraform apply -auto-approve tfplan

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name $(terraform output -raw cluster_name) \
            --region ${{ env.AWS_REGION }}

  # ──────────────────────────────────────────
  # JOB 3: Deploy to PRODUCTION
  # (requires manual approval via GitHub Environment)
  # ──────────────────────────────────────────
  deploy-production:
    name: "Deploy → Production"
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    needs: deploy-staging
    environment: production   # ← maps to GitHub Environment "production" with required reviewers

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.GITHUB_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.7"

      - name: Terraform Init (Production Backend)
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=production/terraform.tfstate" \
            -backend-config="region=${{ secrets.TF_STATE_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}" \
            -backend-config="encrypt=true" \
            -reconfigure

      - name: Terraform Plan (Production)
        run: |
          terraform plan \
            -var="environment=production" \
            -out=tfplan-prod

      - name: Terraform Apply (Production)
        if: github.event.inputs.action != 'plan'
        run: terraform apply -auto-approve tfplan-prod

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name $(terraform output -raw cluster_name) \
            --region ${{ env.AWS_REGION }}